version: "3.1"
services:
  app:    
    container_name: robowealth    
    build: .       
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:3.6
    restart: always
    command: mongod --storageEngine=wiredTiger    
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example           
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    